spring:
  application:
    name: bookstore
  security:
    user:
      name: admin
      password: secret

---
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: acc
